doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/AppBundle/DoctrineMigrations'
    namespace: AppBundle\DoctrineMigrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false # Version >=1.2 Possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false

doctrine:
    dbal:
        schema_filter: ~^(?!t_)~
